version: "3.9"

services:
  db:
    image: postgres:17
    container_name: marketplace-db
    environment:
      POSTGRES_USER: marketplace_dba
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace_dba -d marketplace"]
      interval: 2s
      retries: 10
 
  app:
    build: .
    container_name: marketplace-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: marketplace_dba
      DB_PASSWORD: 12345678
      DB_NAME: marketplace
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
